language: python
branches:
  only:
    - master
install:
  - pip install pipenv
  - pipenv install --dev --deploy
script:
  - echo ${GITHUB_TOKEN}
  - fab build

deploy:
  provider: pages
  skip-cleanup: true
  repo: hackrole/hackrole.github.io
  target-branch: master
  local-dir: output
  github-token: $GITHUB_TOKEN
  keep-history: false
  # fqdn: pages.hackrole.com
