language: python
branches:
  only:
    - master
install:
  - pip install pipenv
  - pipenv install --dev --deploy
script:
  - fab build
  - cd output
  - git add -A
  - git commit -m "update blog"
  - git push origin master

deploy:
  provider: pages
  skip-cleanup: true
  repo: hackrole.github.io
  target-branch: master
  local-dir: output
  github-token: $GITHUB_TOKEN
  keep-history: false
  verbose: true

