language: python
branches:
  only:
    - master
install:
  - pip install pipenv
  - pipenv install --dev --deploy
script:
  - fab build

deploy:
  provider: pages
  skip-cleanup: true
  repo: hackrole.github.io
  local-dir: output
  github-token: $GITHUB_TOKEN
  keep-history: false
  email: hack.role@gmail.com
  name: hackrole

