active_modules: [pygments, tags, blog, latex, disqus]
author: hackrole
canonical_url: http://hr-note.appspot.com
feed:
  name: hackrole's home
  subtitle: 'life is just meet itself.'

modules:
  pygments:
    style: 'friendly'

  disqus:
    shortname: 'hr-note'
